CREATE DATABASE QuanLyThuVien

GO

USE QuanLyThuVien

GO

CREATE TABLE TACGIA
(
    MaTacGia INT IDENTITY NOT NULL PRIMARY KEY,
    TenTacGia NVARCHAR(100)
)

CREATE TABLE KESACH
(
    MaKeSach INT IDENTITY NOT NULL PRIMARY KEY,
    TenKeSach NVARCHAR(100)
)

CREATE TABLE THELOAI
(
    MaKeSach INT FOREIGN KEY REFERENCES KESACH(MaKeSach),
    TenTheLoai NVARCHAR(100)
)

CREATE TABLE KHO
(
    MaKho INT IDENTITY NOT NULL PRIMARY KEY,
    TenKho NVARCHAR(100),
    DiaChiKho NVARCHAR(200)
)

CREATE TABLE NCC
(
    MaNCC INT IDENTITY NOT NULL PRIMARY KEY,
    TenNCC NVARCHAR(100),
    DiaChiNCC NVARCHAR(200),
    SDT_NCC INT
)

CREATE TABLE NXB
(
    MaNXB INT IDENTITY NOT NULL PRIMARY KEY,
    TenNXB NVARCHAR(100),
    DiaChiNXB NVARCHAR(200),
    SDT_NCC INT
)

CREATE TABLE THETHUVIEN
(
    MaThe INT IDENTITY NOT NULL PRIMARY KEY,
    TrangThai NVARCHAR(100),
    NgayHetHan DATE,
    SoLanGiaHan INT
)

CREATE TABLE VIPHAM
(
    MaViPham INT IDENTITY NOT NULL PRIMARY KEY,
    TenViPham NVARCHAR(100),
    GhiChu NVARCHAR(200),
    MaThe INT FOREIGN KEY REFERENCES THETHUVIEN(MaThe)
)

CREATE TABLE DOCGIA
(
    MaDocGia INT IDENTITY NOT NULL PRIMARY KEY,
    HoTenDocGia NVARCHAR(100),
    Lop NVARCHAR(100),
    NgaySinh DATE,
    DiaChi NVARCHAR(200),
    SDT INT,
    MaThe INT FOREIGN KEY REFERENCES THETHUVIEN(MaThe)
)

CREATE TABLE DAUSACH
(
    MaDauSach INT IDENTITY NOT NULL PRIMARY KEY,
    TenDauSach NVARCHAR(100),
    MaNXB INT FOREIGN KEY REFERENCES NXB(MaNXB)
)

CREATE TABLE SACH_TACGIA
(
    MaDauSach INT FOREIGN KEY REFERENCES DAUSACH(MaDauSach) ,
    MaTacGia INT FOREIGN KEY REFERENCES TACGIA(MaTacGia),
    PRIMARY KEY(MaDauSach, MaTacGia)
)

CREATE TABLE PHIEUMUON
(
    MaPhieuMuon INT IDENTITY NOT NULL PRIMARY KEY,
    NgayMuon DATE,
    NgayHanTra DATE,
    MaThe INT FOREIGN KEY REFERENCES THETHUVIEN(MaThe)
)

CREATE TABLE PHIEUTRA
(
    MaPhieuTra INT IDENTITY NOT NULL PRIMARY KEY,
    NgayTra DATE,
    MaThe INT FOREIGN KEY REFERENCES THETHUVIEN(MaThe)
)

CREATE TABLE CUONSACH
(
    MaCuonSach INT IDENTITY NOT NULL PRIMARY KEY,
    TenSach NVARCHAR(100),
    SoTrang INT,
    TinhTrangCuonSach INT,
    MaDauSach INT FOREIGN KEY REFERENCES DAUSACH(MaDauSach),
    MaKeSach INT FOREIGN KEY REFERENCES KESACH(MaKeSach),
    MaPhieuMuon INT FOREIGN KEY REFERENCES PHIEUMUON(MaPhieuMuon),
    MaPhieuTra INT FOREIGN KEY REFERENCES PHIEUTRA(MaPhieuTra),
)

CREATE TABLE PHIEUKIEMKE
(
    MaPhieuKiemKe INT IDENTITY NOT NULL PRIMARY KEY,
    NgayKiemKe DATE,
    SoLuongDau INT,
    SoLuongCuoi INT,
    MaKho INT FOREIGN KEY REFERENCES KHO(MaKho)
)

CREATE TABLE NHANVIEN
(
    MaNhanVien INT IDENTITY NOT NULL PRIMARY KEY,
    TenNhanVien NVARCHAR(100),
    MaKho INT FOREIGN KEY REFERENCES KHO(MaKho)
)

CREATE TABLE QUANLYMUONSACH
(
    MaPhieuMuon INT FOREIGN KEY REFERENCES PHIEUMUON(MaPhieuMuon),
    MaNhanVien INT FOREIGN KEY REFERENCES NHANVIEN(MaNhanVien)
        PRIMARY KEY(MaPhieuMuon, MaNhanVien)
)

CREATE TABLE QUANLYTRASACH
(
    MaPhieuTra INT FOREIGN KEY REFERENCES PHIEUTRA(MaPhieuTra),
    MaNhanVien INT FOREIGN KEY REFERENCES NHANVIEN(MaNhanVien)
        PRIMARY KEY(MaPhieuTra, MaNhanVien)
)

CREATE TABLE PHIEUNHAP
(
    MaKho INT FOREIGN KEY REFERENCES KHO(MaKho),
    MaNCC INT FOREIGN KEY REFERENCES NCC(MaNCC),
    NgayNhap DATE,
    SoLuong INT,
    MaDauSach INT FOREIGN KEY REFERENCES DAUSACH(MaDauSach),
    PRIMARY KEY(MaKho, MaNCC)

)

CREATE TABLE PHIEUXUAT
(
    MaKho INT FOREIGN KEY REFERENCES KHO(MaKho),
    MaKeSach INT FOREIGN KEY REFERENCES KESACH(MaKeSach),
    NgayXuat DATE
        PRIMARY KEY(MaKho, MaKeSach)
)